[book]
authors = ["techtoto"]
language = "en"
multilingual = false
src = "src"
title = "Tobis Rezeptbuch"

[output.html]
additional-css = ["./src/style-print.css"]
[output.pdf]
optional = true
## Set for auto-retrying if failed to generate PDF.
# trying-times = 1
## This backend only support latest Chromium based browsers, not Safari and Firefox currently.
## If needed, please specify the full path.
## If you specify the wrong binary, chances are that there will be a timeout error.
# browser-binary-path = ""
## Assign the static hosting site url so that relative links outside the book can be fixed.
# static_site_url = "https://rust-lang.github.io/mdBook"
## Check Chrome Devtools Protocol Docs for the explanation of the following params:
## https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF
display-header-footer = true
print-background = true
paper-width = 8.26772
paper-height = 11.6929
margin-left = 0.3
margin-right = 0.3
margin-top = 0.5
margin-bottom = 0.5
header-template = "<div style='display:flex;justify-content:center;width:100%;'><p style='font-size:12em;' class='title'></p></div>"
footer-template = "<div style='display:flex;justify-content:right;width:100%;'><p style='font-size:12em;margin-right:5em;' class='pageNumber'></p></div>"
generateTaggedPDF = true
